spring:
  application:
    name: maps-poc
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

# Expose actuator endpoints for health/info by default
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# Swagger/OpenAPI UI: access at /swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Google Maps configuration
# Prefer setting via environment variable GOOGLE_MAPS_API_KEY
# Example: export GOOGLE_MAPS_API_KEY=your_key_here
# or use an application-local.yml (ignored by VCS) to override locally
google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
